### PR TITLE
Enable keyboard shortcut to mute from any tab

### PR DESCRIPTION
**Pull request by nedarb**
Allow a global (throughout all browser windows) mute/unmute toggle keyboard shortcut

### CODE REVIEW

**Comment by stopdropandrew** [comment]
Hi there! Thanks for the pull. Unfortunately, I tried this out and couldn't get it to work.

 Also, I'd like to keep the scope of this extension to the current tab, while the tool has appeal to many folks, and I totally get the use for this type of feature, it's mostly used by educators and students and I'm not super comfortable adding more permissions requirements.

That said, feel free to publish your own version with additional functionality! Or if there's a way to do this without adding the tabs permissions I'd be interested as well.

**Comment by tpott** [comment]
Oh nice! Thanks for the context. Do you think adding an optional permission would be okay (https://developer.chrome.com/extensions/permissions)? I'd imagine a toggle in the popup could re-request permission if someone wants to enable it. 

I'm not sure how to do it without the tabs permission. But I would like to figure out how to get it to work, since I tend to have several tabs open at once. I can try maintaining a fork if optional permissions isn't okay!

I'll give that PR a look and see if I can figure out how to get it to work.

**Comment by tpott** [comment]
So I just played around with this PR and it was pretty interesting. I was able to add another toggle to the options.html file, similar to the "Mute on Join" toggle. That worked pretty well for requesting "tabs" permissions (see the chrome documentation for what the screenshots look like). 

The other change that I think is interesting in this PR is that it uses https://developer.chrome.com/apps/commands . Which seems like Chrome's method for exposing keyboard shortcuts. It allows for capturing from any tab, as well as outside of Chrome, if you enable it, but it _must_ be configured through chrome://extensions/shortcuts . So we wouldn't be able to change the shortcut/hotkey from options.html any more. The other thing is that command handlers seem to be designed to run in a background page, and so it relies pretty heavily on having the "tabs" permission enabled in order to push the command to a meeting.

**Comment by nedarb** [comment]
@tpott I rewired this to use the persistent messaging instead of accessing the tab via `chrome.tabs`. This should (1) add no extra permissions to the extension and (2) allow configurability of what keys to use at a global level for toggling mute. The new PR is #10 .

This would also allow for further key commands like global mute vs. global unmute (instead of toggling). Though, now that I think about it, if you're in 2 meetings and you use global mute/unmute with one meeting muted and the other unmuted, it'll switch which one is muted :)

**Pull request closed without merging**
